pipeline{
    agent any
    tools{
        maven "maven"
    }
    stages{
        stage("Build JAR File"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/MatiasHernandezC/TopEducation.git']])
                dir("monolitica"){
                    sh "mvn clean install"
                }
            }
        }
        stage("Test"){
            steps{
                dir("monolitica"){
                    sh "mvn test"
                }
            }
        }
        stage("Build Docker Image"){
            steps{
                dir("monolitica"){
                    sh "docker build -t motihc/proyecto_top_education ."
                }
            }
        }
        stage("Push Docker Image"){
            steps{
                dir("monolitica"){
                    withCredentials([string(credentialsId: 'dckrhubpassword', variable: 'dckpass')]) {
                        sh "docker login -u motihc -p ${dckpass}"
                    }
                    sh "docker push motihc/proyecto_top_education"
                }
                
            }
        }
    }
    post{
        always{
            dir("monolitica"){
                sh "docker logout"
            }
        }
    }
}
